sudo: false
language: python
python:
    - "2.7"
before_install:
    - pip install pep8
    - pip install pylint

script:
    - find . -name \*.py -exec pep8 {} +
    - find . -name \*.py -exec pylint {} +
